### ISSUE TITLE
cast to Fragment Activity

### ISSUE THREAD

**Issue by alishe79** [infinum/flutter-plugins-locker#15]
in my project , run 

`FlutterLocker.save(SaveSecretRequest("passCode", "passCodeSecret", AndroidPrompt("Authenticate", "Cancel")));`

but get exception under error

`Unhandled Exception: PlatformException(error, com.bibtel.MainActivity cannot be cast to androidx.fragment.app.FragmentActivity, null, java.lang.ClassCastException: com.bibtel.MainActivity cannot be cast to androidx.fragment.app.FragmentActivity`

how fix it.

me noob in the flutter.

**Comment by itsJoKr** [comment]
Go to /android/app/src/main/kotlin/com/**/MainActivity and change:

`import io.flutter.embedding.android.FlutterActivity` to `import io.flutter.embedding.android.FlutterFragmentActivity`
and `FlutterActivity` to ` FlutterFragmentActivity`

**Comment by dnaicker** [comment]
Could this be added to the main source files?
