### ISSUE TITLE
iOS plugin fails to build after Locker iOS library update to v3

### ISSUE THREAD

**Issue by euriasb** [infinum/flutter-plugins-locker#17]
Error:
```
SwiftFlutterLockerPlugin.swift:61:23: error: initializer for conditional binding must have Optional type, not 'String'
                    guard let secret = secret else {
```

This is because after Locker was migrated to swift in v3.0, the `retrieveCurrentSecret` success callback is now not optional [source](https://github.com/infinum/Locker/blob/master/Sources/Locker/Core/Locker.swift#L129).

**Comment by itsJoKr** [comment]
Hey, thanks for using the package.

Fix is out on pub.dev (2.0.1).
