### ISSUE TITLE
Touch ID and Face ID locked

### ISSUE THREAD

**Issue by barteksc** [infinum/flutter-plugins-locker#20]
When using Touch ID, after 3 wrong attempts the prompt is closed and a `LockerException` with the `authenticationFailed` reason is thrown. After 2 wrong attempts more, Touch ID will be locked for all apps (it may be unlocked using PIN). After that, every time I call `FlutterLocker.retrieve`, an exception with the `authenticationFailed` reason is thrown - it's ok, but now my question is how I can differentiate between those two cases. It must be possible in some way, as there are apps that are showing a dialog with a message that Touch ID is locked and cannot be used right now.

With Face ID it behaves similarly, but in the first case an exception with the `authenticationCanceled` reason is thrown.

**Comment by suphawutP** [comment]
I have faced a similar but for me, I want to separate for face id is locked when the user exceeds the attempt to fail the face scan and permission face scan doesn't allow because 2 of these `PlatformException` is the same error code is "1".

**Comment by zenled** [comment]
The latest version of this package includes some fixes related to exception handling.
Please re-open this issue if you are still having problems.
