### ISSUE TITLE
failed to build module 'System'; this SDK is not supported by the compiler - Xcode 

### ISSUE THREAD

**Issue by batkholboo** [infinum/flutter-plugins-locker#21]
Getting this error:

/ios/Pods/Locker/Sources/Locker/Helpers/LockerHelpers.swift:11:8: error: failed to build
    module 'System'; this SDK is not supported by the compiler (the SDK is built with 'Apple Swift version 5.5.2 (swiftlang-1300.0.46.202
    clang-1300.0.29.30)', while this compiler is 'Apple Swift version 5.5.2 (swiftlang-1300.0.47.5 clang-1300.0.29.30)'). Please select a
    toolchain which matches the SDK.
    import System
           ^
    remark: Incremental compilation has been disabled: it is not compatible with whole module optimization
    Command CompileSwiftSources failed with a nonzero exit code
    note: Using new build system
    note: Planning
    note: Build preparation complete
    note: Building targets in dependency order

Environment
flutter_locker version  2.0.3
XCode version 13.2.1 
Apple Swift version 5.5.2
Flutter Channel stable, 2.8.1, on macOS 12.0.1

**Comment by tomquas** [comment]
ran into the same thing. this solved it for me:

 1. open example/ios/Runner.xcworkspace
 2. Runner.project: Update to recommended settings - click this, confirm, Cmd-R

voila. message to self: still paying annual 99 for being f**ed by every single xcode update... am i nuts?

**Comment by itsJoKr** [comment]
This should be fixed with 2.0.4
