### ISSUE TITLE
Build fails for Android on M1 Macs

### ISSUE THREAD

**Issue by euriasb** [infinum/flutter-plugins-locker#23]
Build fails for Android on M1 Macs with the following error:

```
Execution failed for task ':flutter_locker:generateDebugProto'.
> Could not resolve all files for configuration ':flutter_locker:protobufToolsLocator_protoc'.
   > Could not find protoc-3.9.1-osx-aarch_64.exe (com.google.protobuf:protoc:3.9.1).
     Searched in the following locations:
         [https://jcenter.bintray.com/com/google/protobuf/protoc/3.9.1/protoc-3.9.1-osx-aarch_64.exe]()
```

After some googling, the issue is that there are no binaries for M1 Macs, there are however x86 compatible binaries, [this github issue](https://github.com/grpc/grpc-java/issues/7690) explains how to make protobuf select the appropriate binary, I did it locally and it worked successfully.

**Comment by tudor07** [comment]
I'm having the same problem but the workarounds did not work for me, I'm stuck

**Comment by euriasb** [comment]
> I'm having the same problem but the workarounds did not work for me, I'm stuck

The exact thing I do when I test on Android is I just hard code this on the gradle file:

```
protobuf {
    // Configure the protoc executable
    protoc {
        // Download from repositories
        artifact = 'com.google.protobuf:protoc:3.9.1:osx-x86_64'
    }
    plugins {
        javalite {
            // The codegen for lite comes as a separate artifact
            artifact = 'com.google.protobuf:protoc-gen-javalite:3.0.0:osx-x86_64'
        }
    }
    generateProtoTasks {
        all().each { task ->
            task.plugins {
                javalite { }
            }
        }
    }
}
```

So, just hardcode `:osx-x86_64` after the `protoc` and `javalite` artifacts.

Hope this helps you @tudor07

**Comment by tudor07** [comment]
@euriasb unfortuntaly that does not work for me

> * What went wrong:
> A problem occurred evaluating project ':app'.
> > Could not find method protobuf() for arguments [build_a3bkpzk12frubfik9jilgxszt$_run_closure6@3d992407] on project ':app' of type org.gradle.api.Project.
>

**Comment by tudor07** [comment]
@zenled @itsJoKr any change you can look into this issue?

**Comment by Kundan-Android** [comment]
Any luck on this, above mentioned workaround is not working for me.

**Comment by itsJoKr** [comment]
Can you try this until we get out the new version:
```
  flutter_locker:
      git:
        url: https://github.com/infinum/flutter-plugins-locker
        ref: 781f02ffa14bef819a9ee5d4c9ac98a42cfc9e57
```

**Comment by itsJoKr** [comment]
You can also try 2.0.4
```
flutter_locker: ^2.0.4
```
