### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by guilo8914** [infinum/flutter-plugins-locker#24]
I've been trying for a while to check for which exception the user gets (as in he cancelled the auth, doesn't have biometrics, etc) but I can't see anywhere if there are ways to compare which exception has been catched (such as LockerException: Authentication canceled by user.
or PlatformException(3, co.infinum.goldfinger.NoEnrolledFingerprintException: User has no enrolled fingerprint., null, null).  Is there an easier way to do this other than comparing strings and checking what word it has?

And on the subject of it, shouldn't a popup open to configure fingerprints if there aren't any configured in the android?

Thanks in advance

**Comment by itsJoKr** [comment]
Hey @guilo8914 

LockerException.reason is an enum that you'll want to handle.

All the other errors will unfortunately be strings in PlatformException. Reason is that each platform behaves a bit differently and has it's own errors so it's a bit hard to unify them all into one enum.

> And on the subject of it, shouldn't a popup open to configure fingerprints if there aren't any configured in the android?
This library will not do that. I haven't seen Android library that does this automatically, it was always up to developer to do that if they want it.
