### ISSUE TITLE
faceid does not pop on pixel 7pro (Android) 

### ISSUE THREAD

**Issue by itzikkle** [infinum/flutter-plugins-locker#39]
Hi,
FaceId popup does not appear on pixel 7 pro. 
I first check for biometrics and then try to save using biometrics.

 try {
    String key = 'pwdkey';
    String secret = '1111';
    await FlutterLocker.save(
    SaveSecretRequest(
    key: key,
    secret: secret,
    androidPrompt: AndroidPrompt(
    title: authPrompt.title,
    cancelLabel: "Cancel",
    descriptionLabel: authPrompt.description)),
    );
    return true;
  } on Exception catch (exception) {
    return false;
  }

**Comment by itsJoKr** [comment]
The underlying Android library only uses strong authentication. Face recognition on that phone is just a plain camera and can not be considered strong, it can be easily proved false-positive with a photo of a person.

For strong face authentication, you need to have a few more sensors (like the NIR sensor) that iPhone has. The only Android that has that is Pixel 4.
