### ISSUE TITLE
on some random occasions after a valid fingerprint callback not triggered 

### ISSUE THREAD

**Issue by shlomi-ts** [infinum/flutter-plugins-locker#41]
We experiences a weird issue that comes and goes, 
on some occasions after a successful fingerprint validation (using FlutterLocker.save(...)) - no success callback is triggered.

did you encountered that behavior?

Thanks in advance

**Comment by zenled** [comment]
I was unable to reproduce this issue.
If the problem persists with the latest version of this package, feel free to re-open the issue.
