### ISSUE TITLE
How to identify biometric type installed on device?

### ISSUE THREAD

**Issue by petro-i** [infinum/flutter-plugins-locker#7]
Hi,
Thank you for this very useful plugin!!!

There is one feature missing, as for me, to identify the biometric type, for sure it is needed for iOS only (at this moment).
Use case of this feature - to show user appropriate text in settings to enable Touch/Face ID.

Could you please try to implement such functionality?

**Comment by itsJoKr** [comment]
Hi there. Thanks for using the package and thanks for the PR.

We did not need such feature, so it's not implemented.

If you need this right now, I suggest you to add [local_auth](https://pub.dev/packages/local_auth) package and just use the part to check if its touch or face.

I will mark this as an enhancement, but it might take a while to implement as it's peak vacation season.

**Comment by zenled** [comment]
As mentioned, this package does not support identifying biometric types.
We recommend using the [local_auth](https://pub.dev/packages/local_auth) to do that.
