### ISSUE TITLE
Error on Android < 9 - Rejecting re-init on previously-failed class java.lang.Class<androidx.core.view.ViewCompat$2>: java.lang.NoClassDefFoundError:

### ISSUE THREAD

**Issue by petro-i** [infinum/flutter-plugins-locker#8]
There is error reported to log running app using plugin, including plugin example itself, on Android version less than 9.

Just run plugin example on any android version  < 9, f.e. 8.1

Could you please have a look?

<details>
  <summary><b>Click to expand error output</b></summary>
`I/zygote  (14541): Rejecting re-init on previously-failed class java.lang.Class<androidx.core.view.ViewCompat$2>: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/view/View$OnUnhandledKeyEventListener;
I/zygote  (14541):   at void androidx.core.view.ViewCompat.setOnApplyWindowInsetsListener(android.view.View, androidx.core.view.OnApplyWindowInsetsListener) (ViewCompat.java:2421)
I/zygote  (14541):   at android.view.ViewGroup androidx.appcompat.app.AppCompatDelegateImpl.createSubDecor() (AppCompatDelegateImpl.java:779)
I/zygote  (14541):   at void androidx.appcompat.app.AppCompatDelegateImpl.ensureSubDecor() (AppCompatDelegateImpl.java:659)
I/zygote  (14541):   at void androidx.appcompat.app.AppCompatDelegateImpl.setContentView(int) (AppCompatDelegateImpl.java:552)
I/zygote  (14541):   at void androidx.appcompat.app.AppCompatDialog.setContentView(int) (AppCompatDialog.java:95)
I/zygote  (14541):   at void androidx.appcompat.app.AlertController.installContent() (AlertController.java:232)
I/zygote  (14541):   at void androidx.appcompat.app.AlertDialog.onCreate(android.os.Bundle) (AlertDialog.java:279)
I/zygote  (14541):   at void android.app.Dialog.dispatchOnCreate(android.os.Bundle) (Dialog.java:403)
I/zygote  (14541):   at void android.app.Dialog.show() (Dialog.java:302)
I/zygote  (14541):   at void androidx.fragment.app.DialogFragment.onStart() (DialogFragment.java:486)
I/zygote  (14541):   at void androidx.fragment.app.Fragment.performStart() (Fragment.java:2632)
I/zygote  (14541):   at void androidx.fragment.app.FragmentManagerImpl.moveToState(androidx.fragment.app.Fragment, int, int, int, boolean) (FragmentManagerImpl.java:915)
I/zygote  (14541):   at void androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(androidx.fragment.app.Fragment) (FragmentManagerImpl.java:1238)
I/zygote  (14541):   at void androidx.fragment.app.FragmentManagerImpl.moveToState(int, boolean) (FragmentManagerImpl.java:1303)
I/zygote  (14541):   at void androidx.fragment.app.BackStackRecord.executeOps() (BackStackRecord.java:439)
I/zygote  (14541):   at void androidx.fragment.app.FragmentManagerImpl.executeOps(java.util.ArrayList, java.util.ArrayList, int, int) (FragmentManagerImpl.java:2079)
I/zygote  (14541):   at void androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(java.util.ArrayList, java.util.ArrayList, int, int) (FragmentManagerImpl.java:1869)
I/zygote  (14541):   at void androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(java.util.ArrayList, java.util.ArrayList) (FragmentManagerImpl.java:1824)
I/zygote  (14541):   at boolean androidx.fragment.app.FragmentManagerImpl.execPendingActions() (FragmentManagerImpl.java:1727)
I/zygote  (14541):   at boolean androidx.fragment.app.FragmentManagerImpl.executePendingTransactions() (FragmentManagerImpl.java:183)
I/zygote  (14541):   at void androidx.biometric.BiometricPrompt.authenticateInternal(androidx.biometric.BiometricPrompt$PromptInfo, androidx.biometric.BiometricPrompt$CryptoObject) (BiometricPrompt.java:793)
I/zygote  (14541):   at void androidx.biometric.BiometricPrompt.authenticate(androidx.biometric.BiometricPrompt$PromptInfo, androidx.biometric.BiometricPrompt$CryptoObject) (BiometricPrompt.java:648)
I/zygote  (14541):   at void co.infinum.goldfinger.GoldfingerImpl$3.run() (GoldfingerImpl.java:228)
I/zygote  (14541):   at void android.os.Handler.handleCallback(android.os.Message) (Handler.java:790)
I/zygote  (14541):   at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:99)
I/zygote  (14541):   at void android.os.Looper.loop() (Looper.java:164)
I/zygote  (14541):   at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6494)
I/zygote  (14541):   at java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[]) (Method.java:-2)
I/zygote  (14541):   at void com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run() (RuntimeInit.java:438)
I/zygote  (14541):   at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:807)
I/zygote  (14541): Caused by: java.lang.ClassNotFoundException: Didn't find class "android.view.View$OnUnhandledKeyEventListener" on path: DexPathList[[zip file "/data/app/com.example.flutter_locker_example-aN0cfjmoIpx7akkDLyfw5g==/base.apk"],nativeLibraryDirectories=[/data/app/com.example.flutter_locker_example-aN0cfjmoIpx7akkDLyfw5g==/lib/x86, /data/app/com.example.flutter_locker_example-aN0cfjmoIpx7akkDLyfw5g==/base.apk!/lib/x86, /system/lib, /vendor/lib]]
I/zygote  (14541):   at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:125)
I/zygote  (14541):   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:379)
I/zygote  (14541):   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:312)
I/zygote  (14541):   at void androidx.core.view.ViewCompat.setOnApplyWindowInsetsListener(android.view.View, androidx.core.view.OnApplyWindowInsetsListener) (ViewCompat.java:2421)
I/zygote  (14541):   at android.view.ViewGroup androidx.appcompat.app.AppCompatDelegateImpl.createSubDecor() (AppCompatDelegateImpl.java:779)
I/zygote  (14541):   at void androidx.appcompat.app.AppCompatDelegateImpl.ensureSubDecor() (AppCompatDelegateImpl.java:659)
I/zygote  (14541):   at void androidx.appcompat.app.AppCompatDelegateImpl.setContentView(int) (AppCompatDelegateImpl.java:552)
I/zygote  (14541):   at void androidx.appcompat.app.AppCompatDialog.setContentView(int) (AppCompatDialog.java:95)
I/zygote  (14541):   at void androidx.appcompat.app.AlertController.installContent() (AlertController.java:232)
I/zygote  (14541):   at void androidx.appcompat.app.AlertDialog.onCreate(android.os.Bundle) (AlertDialog.java:279)
I/zygote  (14541):   at void android.app.Dialog.dispatchOnCreate(android.os.Bundle) (Dialog.java:403)
I/zygote  (14541):   at void android.app.Dialog.show() (Dialog.java:302)
I/zygote  (14541):   at void androidx.fragment.app.DialogFragment.onStart() (DialogFragment.java:486)
I/zygote  (14541):   at void androidx.fragment.app.Fragment.performStart() (Fragment.java:2632)
I/zygote  (14541):   at void androidx.fragment.app.FragmentManagerImpl.moveToState(androidx.fragment.app.Fragment, int, int, int, boolean) (FragmentManagerImpl.java:915)
I/zygote  (14541):   at void androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(androidx.fragment.app.Fragment) (FragmentManagerImpl.java:1238)
I/zygote  (14541):   at void androidx.fragment.app.FragmentManagerImpl.moveToState(int, boolean) (FragmentManagerImpl.java:1303)
I/zygote  (14541):   at void androidx.fragment.app.BackStackRecord.executeOps() (BackStackRecord.java:439)
I/zygote  (14541):   at void androidx.fragment.app.FragmentManagerImpl.executeOps(java.util.ArrayList, java.util.ArrayList, int, int) (FragmentManagerImpl.java:2079)
I/zygote  (14541):   at void androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(java.util.ArrayList, java.util.ArrayList, int, int) (FragmentManagerImpl.java:1869)
I/zygote  (14541):   at void androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(java.util.ArrayList, java.util.ArrayList) (FragmentManagerImpl.java:1824)
I/zygote  (14541):   at boolean androidx.fragment.app.FragmentManagerImpl.execPendingActions() (FragmentManagerImpl.java:1727)
I/zygote  (14541):   at boolean androidx.fragment.app.FragmentManagerImpl.executePendingTransactions() (FragmentManagerImpl.java:183)
I/zygote  (14541):   at void androidx.biometric.BiometricPrompt.authenticateInternal(androidx.biometric.BiometricPrompt$PromptInfo, androidx.biometric.BiometricPrompt$CryptoObject) (BiometricPrompt.java:793)
I/zygote  (14541):   at void androidx.biometric.BiometricPrompt.authenticate(androidx.biometric.BiometricPrompt$PromptInfo, androidx.biometric.BiometricPrompt$CryptoObject) (BiometricPrompt.java:648)
I/zygote  (14541):   at void co.infinum.goldfinger.GoldfingerImpl$3.run() (GoldfingerImpl.java:228)
I/zygote  (14541):   at void android.os.Handler.handleCallback(android.os.Message) (Handler.java:790)
I/zygote  (14541):   at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:99)
I/zygote  (14541):   at void android.os.Looper.loop() (Looper.java:164)
I/zygote  (14541):   at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6494)
I/zygote  (14541):   at java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[]) (Method.java:-2)
I/zygote  (14541):   at void com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run() (RuntimeInit.java:438)
I/zygote  (14541):   at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:807)
I/zygote  (14541): 
I/zygote  (14541): Rejecting re-init on previously-failed class java.lang.Class<androidx.core.view.ViewCompat$2>: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/view/View$OnUnhandledKeyEventListener;
I/zygote  (14541):   at void androidx.core.view.ViewCompat.setOnApplyWindowInsetsListener(android.view.View, androidx.core.view.OnApplyWindowInsetsListener) (ViewCompat.java:2421)
I/zygote  (14541):   at android.view.ViewGroup androidx.appcompat.app.AppCompatDelegateImpl.createSubDecor() (AppCompatDelegateImpl.java:779)
I/zygote  (14541):   at void androidx.appcompat.app.AppCompatDelegateImpl.ensureSubDecor() (AppCompatDelegateImpl.java:659)
I/zygote  (14541):   at void androidx.appcompat.app.AppCompatDelegateImpl.setContentView(int) (AppCompatDelegateImpl.java:552)
I/zygote  (14541):   at void androidx.appcompat.app.AppCompatDialog.setContentView(int) (AppCompatDialog.java:95)
I/zygote  (14541):   at void androidx.appcompat.app.AlertController.installContent() (AlertController.java:232)
I/zygote  (14541):   at void androidx.appcompat.app.AlertDialog.onCreate(android.os.Bundle) (AlertDialog.java:279)
I/zygote  (14541):   at void android.app.Dialog.dispatchOnCreate(android.os.Bundle) (Dialog.java:403)
I/zygote  (14541):   at void android.app.Dialog.show() (Dialog.java:302)
I/zygote  (14541):   at void androidx.fragment.app.DialogFragment.onStart() (DialogFragment.java:486)
I/zygote  (14541):   at void androidx.fragment.app.Fragment.performStart() (Fragment.java:2632)
I/zygote  (14541):   at void androidx.fragment.app.FragmentManagerImpl.moveToState(androidx.fragment.app.Fragment, int, int, int, boolean) (FragmentManagerImpl.java:915)
I/zygote  (14541):   at void androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(androidx.fragment.app.Fragment) (FragmentManagerImpl.java:1238)
I/zygote  (14541):   at void androidx.fragment.app.FragmentManagerImpl.moveToState(int, boolean) (FragmentManagerImpl.java:1303)
I/zygote  (14541):   at void androidx.fragment.app.BackStackRecord.executeOps() (BackStackRecord.java:439)
I/zygote  (14541):   at void androidx.fragment.app.FragmentManagerImpl.executeOps(java.util.ArrayList, java.util.ArrayList, int, int) (FragmentManagerImpl.java:2079)
I/zygote  (14541):   at void androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(java.util.ArrayList, java.util.ArrayList, int, int) (FragmentManagerImpl.java:1869)
I/zygote  (14541):   at void androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(java.util.ArrayList, java.util.ArrayList) (FragmentManagerImpl.java:1824)
I/zygote  (14541):   at boolean androidx.fragment.app.FragmentManagerImpl.execPendingActions() (FragmentManagerImpl.java:1727)
I/zygote  (14541):   at boolean androidx.fragment.app.FragmentManagerImpl.executePendingTransactions() (FragmentManagerImpl.java:183)
I/zygote  (14541):   at void androidx.biometric.BiometricPrompt.authenticateInternal(androidx.biometric.BiometricPrompt$PromptInfo, androidx.biometric.BiometricPrompt$CryptoObject) (BiometricPrompt.java:793)
I/zygote  (14541):   at void androidx.biometric.BiometricPrompt.authenticate(androidx.biometric.BiometricPrompt$PromptInfo, androidx.biometric.BiometricPrompt$CryptoObject) (BiometricPrompt.java:648)
I/zygote  (14541):   at void co.infinum.goldfinger.GoldfingerImpl$3.run() (GoldfingerImpl.java:228)
I/zygote  (14541):   at void android.os.Handler.handleCallback(android.os.Message) (Handler.java:790)
I/zygote  (14541):   at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:99)
I/zygote  (14541):   at void android.os.Looper.loop() (Looper.java:164)
I/zygote  (14541):   at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6494)
I/zygote  (14541):   at java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[]) (Method.java:-2)
I/zygote  (14541):   at void com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run() (RuntimeInit.java:438)
I/zygote  (14541):   at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:807)
I/zygote  (14541): Caused by: java.lang.ClassNotFoundException: Didn't find class "android.view.View$OnUnhandledKeyEventListener" on path: DexPathList[[zip file "/data/app/com.example.flutter_locker_example-aN0cfjmoIpx7akkDLyfw5g==/base.apk"],nativeLibraryDirectories=[/data/app/com.example.flutter_locker_example-aN0cfjmoIpx7akkDLyfw5g==/lib/x86, /data/app/com.example.flutter_locker_example-aN0cfjmoIpx7akkDLyfw5g==/base.apk!/lib/x86, /system/lib, /vendor/lib]]
I/zygote  (14541):   at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:125)
I/zygote  (14541):   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:379)
I/zygote  (14541):   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:312)
I/zygote  (14541):   at void androidx.core.view.ViewCompat.setOnApplyWindowInsetsListener(android.view.View, androidx.core.view.OnApplyWindowInsetsListener) (ViewCompat.java:2421)
I/zygote  (14541):   at android.view.ViewGroup androidx.appcompat.app.AppCompatDelegateImpl.createSubDecor() (AppCompatDelegateImpl.java:779)
I/zygote  (14541):   at void androidx.appcompat.app.AppCompatDelegateImpl.ensureSubDecor() (AppCompatDelegateImpl.java:659)
I/zygote  (14541):   at void androidx.appcompat.app.AppCompatDelegateImpl.setContentView(int) (AppCompatDelegateImpl.java:552)
I/zygote  (14541):   at void androidx.appcompat.app.AppCompatDialog.setContentView(int) (AppCompatDialog.java:95)
I/zygote  (14541):   at void androidx.appcompat.app.AlertController.installContent() (AlertController.java:232)
I/zygote  (14541):   at void androidx.appcompat.app.AlertDialog.onCreate(android.os.Bundle) (AlertDialog.java:279)
I/zygote  (14541):   at void android.app.Dialog.dispatchOnCreate(android.os.Bundle) (Dialog.java:403)
I/zygote  (14541):   at void android.app.Dialog.show() (Dialog.java:302)
I/zygote  (14541):   at void androidx.fragment.app.DialogFragment.onStart() (DialogFragment.java:486)
I/zygote  (14541):   at void androidx.fragment.app.Fragment.performStart() (Fragment.java:2632)
I/zygote  (14541):   at void androidx.fragment.app.FragmentManagerImpl.moveToState(androidx.fragment.app.Fragment, int, int, int, boolean) (FragmentManagerImpl.java:915)
I/zygote  (14541):   at void androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(androidx.fragment.app.Fragment) (FragmentManagerImpl.java:1238)
I/zygote  (14541):   at void androidx.fragment.app.FragmentManagerImpl.moveToState(int, boolean) (FragmentManagerImpl.java:1303)
I/zygote  (14541):   at void androidx.fragment.app.BackStackRecord.executeOps() (BackStackRecord.java:439)
I/zygote  (14541):   at void androidx.fragment.app.FragmentManagerImpl.executeOps(java.util.ArrayList, java.util.ArrayList, int, int) (FragmentManagerImpl.java:2079)
I/zygote  (14541):   at void androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(java.util.ArrayList, java.util.ArrayList, int, int) (FragmentManagerImpl.java:1869)
I/zygote  (14541):   at void androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(java.util.ArrayList, java.util.ArrayList) (FragmentManagerImpl.java:1824)
I/zygote  (14541):   at boolean androidx.fragment.app.FragmentManagerImpl.execPendingActions() (FragmentManagerImpl.java:1727)
I/zygote  (14541):   at boolean androidx.fragment.app.FragmentManagerImpl.executePendingTransactions() (FragmentManagerImpl.java:183)
I/zygote  (14541):   at void androidx.biometric.BiometricPrompt.authenticateInternal(androidx.biometric.BiometricPrompt$PromptInfo, androidx.biometric.BiometricPrompt$CryptoObject) (BiometricPrompt.java:793)
I/zygote  (14541):   at void androidx.biometric.BiometricPrompt.authenticate(androidx.biometric.BiometricPrompt$PromptInfo, androidx.biometric.BiometricPrompt$CryptoObject) (BiometricPrompt.java:648)
I/zygote  (14541):   at void co.infinum.goldfinger.GoldfingerImpl$3.run() (GoldfingerImpl.java:228)
I/zygote  (14541):   at void android.os.Handler.handleCallback(android.os.Message) (Handler.java:790)
I/zygote  (14541):   at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:99)
I/zygote  (14541):   at void android.os.Looper.loop() (Looper.java:164)
I/zygote  (14541):   at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6494)
I/zygote  (14541):   at java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[]) (Method.java:-2)
I/zygote  (14541):   at void com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run() (RuntimeInit.java:438)
I/zygote  (14541):   at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:807)
I/zygote  (14541): 
I/zygote  (14541): Rejecting re-init on previously-failed class java.lang.Class<androidx.core.view.ViewCompat$2>: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/view/View$OnUnhandledKeyEventListener;
I/zygote  (14541):   at void androidx.core.view.ViewCompat.setOnApplyWindowInsetsListener(android.view.View, androidx.core.view.OnApplyWindowInsetsListener) (ViewCompat.java:2421)
I/zygote  (14541):   at android.view.ViewGroup androidx.appcompat.app.AppCompatDelegateImpl.createSubDecor() (AppCompatDelegateImpl.java:779)
I/zygote  (14541):   at void androidx.appcompat.app.AppCompatDelegateImpl.ensureSubDecor() (AppCompatDelegateImpl.java:659)
I/zygote  (14541):   at void androidx.appcompat.app.AppCompatDelegateImpl.setContentView(int) (AppCompatDelegateImpl.java:552)
I/zygote  (14541):   at void androidx.appcompat.app.AppCompatDialog.setContentView(int) (AppCompatDialog.java:95)
I/zygote  (14541):   at void androidx.appcompat.app.AlertController.installContent() (AlertController.java:232)
I/zygote  (14541):   at void androidx.appcompat.app.AlertDialog.onCreate(android.os.Bundle) (AlertDialog.java:279)
I/zygote  (14541):   at void android.app.Dialog.dispatchOnCreate(android.os.Bundle) (Dialog.java:403)
I/zygote  (14541):   at void android.app.Dialog.show() (Dialog.java:302)
I/zygote  (14541):   at void androidx.fragment.app.DialogFragment.onStart() (DialogFragment.java:486)
I/zygote  (14541):   at void androidx.fragment.app.Fragment.performStart() (Fragment.java:2632)
I/zygote  (14541):   at void androidx.fragment.app.FragmentManagerImpl.moveToState(androidx.fragment.app.Fragment, int, int, int, boolean) (FragmentManagerImpl.java:915)
I/zygote  (14541):   at void androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(androidx.fragment.app.Fragment) (FragmentManagerImpl.java:1238)
I/zygote  (14541):   at void androidx.fragment.app.FragmentManagerImpl.moveToState(int, boolean) (FragmentManagerImpl.java:1303)
I/zygote  (14541):   at void androidx.fragment.app.BackStackRecord.executeOps() (BackStackRecord.java:439)
I/zygote  (14541):   at void androidx.fragment.app.FragmentManagerImpl.executeOps(java.util.ArrayList, java.util.ArrayList, int, int) (FragmentManagerImpl.java:2079)
I/zygote  (14541):   at void androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(java.util.ArrayList, java.util.ArrayList, int, int) (FragmentManagerImpl.java:1869)
I/zygote  (14541):   at void androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(java.util.ArrayList, java.util.ArrayList) (FragmentManagerImpl.java:1824)
I/zygote  (14541):   at boolean androidx.fragment.app.FragmentManagerImpl.execPendingActions() (FragmentManagerImpl.java:1727)
I/zygote  (14541):   at boolean androidx.fragment.app.FragmentManagerImpl.executePendingTransactions() (FragmentManagerImpl.java:183)
I/zygote  (14541):   at void androidx.biometric.BiometricPrompt.authenticateInternal(androidx.biometric.BiometricPrompt$PromptInfo, androidx.biometric.BiometricPrompt$CryptoObject) (BiometricPrompt.java:793)
I/zygote  (14541):   at void androidx.biometric.BiometricPrompt.authenticate(androidx.biometric.BiometricPrompt$PromptInfo, androidx.biometric.BiometricPrompt$CryptoObject) (BiometricPrompt.java:648)
I/zygote  (14541):   at void co.infinum.goldfinger.GoldfingerImpl$3.run() (GoldfingerImpl.java:228)
I/zygote  (14541):   at void android.os.Handler.handleCallback(android.os.Message) (Handler.java:790)
I/zygote  (14541):   at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:99)
I/zygote  (14541):   at void android.os.Looper.loop() (Looper.java:164)
I/zygote  (14541):   at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6494)
I/zygote  (14541):   at java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[]) (Method.java:-2)
I/zygote  (14541):   at void com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run() (RuntimeInit.java:438)
I/zygote  (14541):   at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:807)
I/zygote  (14541): Caused by: java.lang.ClassNotFoundException: Didn't find class "android.view.View$OnUnhandledKeyEventListener" on path: DexPathList[[zip file "/data/app/com.example.flutter_locker_example-aN0cfjmoIpx7akkDLyfw5g==/base.apk"],nativeLibraryDirectories=[/data/app/com.example.flutter_locker_example-aN0cfjmoIpx7akkDLyfw5g==/lib/x86, /data/app/com.example.flutter_locker_example-aN0cfjmoIpx7akkDLyfw5g==/base.apk!/lib/x86, /system/lib, /vendor/lib]]
I/zygote  (14541):   at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:125)
I/zygote  (14541):   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:379)
I/zygote  (14541):   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:312)
I/zygote  (14541):   at void androidx.core.view.ViewCompat.setOnApplyWindowInsetsListener(android.view.View, androidx.core.view.OnApplyWindowInsetsListener) (ViewCompat.java:2421)
I/zygote  (14541):   at android.view.ViewGroup androidx.appcompat.app.AppCompatDelegateImpl.createSubDecor() (AppCompatDelegateImpl.java:779)
I/zygote  (14541):   at void androidx.appcompat.app.AppCompatDelegateImpl.ensureSubDecor() (AppCompatDelegateImpl.java:659)
I/zygote  (14541):   at void androidx.appcompat.app.AppCompatDelegateImpl.setContentView(int) (AppCompatDelegateImpl.java:552)
I/zygote  (14541):   at void androidx.appcompat.app.AppCompatDialog.setContentView(int) (AppCompatDialog.java:95)
I/zygote  (14541):   at void androidx.appcompat.app.AlertController.installContent() (AlertController.java:232)
I/zygote  (14541):   at void androidx.appcompat.app.AlertDialog.onCreate(android.os.Bundle) (AlertDialog.java:279)
I/zygote  (14541):   at void android.app.Dialog.dispatchOnCreate(android.os.Bundle) (Dialog.java:403)
I/zygote  (14541):   at void android.app.Dialog.show() (Dialog.java:302)
I/zygote  (14541):   at void androidx.fragment.app.DialogFragment.onStart() (DialogFragment.java:486)
I/zygote  (14541):   at void androidx.fragment.app.Fragment.performStart() (Fragment.java:2632)
I/zygote  (14541):   at void androidx.fragment.app.FragmentManagerImpl.moveToState(androidx.fragment.app.Fragment, int, int, int, boolean) (FragmentManagerImpl.java:915)
I/zygote  (14541):   at void androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(androidx.fragment.app.Fragment) (FragmentManagerImpl.java:1238)
I/zygote  (14541):   at void androidx.fragment.app.FragmentManagerImpl.moveToState(int, boolean) (FragmentManagerImpl.java:1303)
I/zygote  (14541):   at void androidx.fragment.app.BackStackRecord.executeOps() (BackStackRecord.java:439)
I/zygote  (14541):   at void androidx.fragment.app.FragmentManagerImpl.executeOps(java.util.ArrayList, java.util.ArrayList, int, int) (FragmentManagerImpl.java:2079)
I/zygote  (14541):   at void androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(java.util.ArrayList, java.util.ArrayList, int, int) (FragmentManagerImpl.java:1869)
I/zygote  (14541):   at void androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(java.util.ArrayList, java.util.ArrayList) (FragmentManagerImpl.java:1824)
I/zygote  (14541):   at boolean androidx.fragment.app.FragmentManagerImpl.execPendingActions() (FragmentManagerImpl.java:1727)
I/zygote  (14541):   at boolean androidx.fragment.app.FragmentManagerImpl.executePendingTransactions() (FragmentManagerImpl.java:183)
I/zygote  (14541):   at void androidx.biometric.BiometricPrompt.authenticateInternal(androidx.biometric.BiometricPrompt$PromptInfo, androidx.biometric.BiometricPrompt$CryptoObject) (BiometricPrompt.java:793)
I/zygote  (14541):   at void androidx.biometric.BiometricPrompt.authenticate(androidx.biometric.BiometricPrompt$PromptInfo, androidx.biometric.BiometricPrompt$CryptoObject) (BiometricPrompt.java:648)
I/zygote  (14541):   at void co.infinum.goldfinger.GoldfingerImpl$3.run() (GoldfingerImpl.java:228)
I/zygote  (14541):   at void android.os.Handler.handleCallback(android.os.Message) (Handler.java:790)
I/zygote  (14541):   at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:99)
I/zygote  (14541):   at void android.os.Looper.loop() (Looper.java:164)
I/zygote  (14541):   at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6494)
I/zygote  (14541):   at java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[]) (Method.java:-2)
I/zygote  (14541):   at void com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run() (RuntimeInit.java:438)
I/zygote  (14541):   at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:807)`
</details>

**Comment by itsJoKr** [comment]
Will take a look. I hope I can reproduce this on the emulator as I don't have such device in remote office.

**Comment by totalerex** [comment]
Thank you, 
emulator should be OK, I have observed it on emulator also.

**Comment by zenled** [comment]
I encountered a similar issue on an Android emulator but could not reproduce it on a real device.
Please test it on a real device with the latest version of this package, and re-open this issue if the problem persists.
