### ISSUE TITLE
 E/FingerprintDialogFrag(14973): Failed to dismiss fingerprint dialog fragment. Fragment manager was null.

### ISSUE THREAD

**Issue by totalerex** [infinum/flutter-plugins-locker#9]
Hi

This is another pre-9 Android error, this one is generated on closing fingerprint dialog.

Just run plugin example on any android version  < 9, f.e. 8.1

E/FingerprintDialogFrag(14973): Failed to dismiss fingerprint dialog fragment. Fragment manager was null.

**Comment by itsJoKr** [comment]
Is this just log? Does it make an app crash or anything severe like that or app can function normally?

Just thinking out loud: There is one known minor bug in Goldfinger, this could be it.

**Comment by totalerex** [comment]
In moment this is just log, but in a day or two I will have some statistics from alpha testers and then it will be more clear.

**Comment by itsJoKr** [comment]
Closing because this is bug in Goldfinger, and the Locker doesn't fail.
